import "./globals.css";
import {App} from "./app";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body>
        <App>
          {children}
        </App>
      </body>
    </html>
  );
}